<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="jdr" nsURI="http://jdr/1.0" nsPrefix="jdr">
  <eClassifiers xsi:type="ecore:EClass" name="Campagne">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarii" upperBound="-1"
        eType="#//Scenario" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annexes" upperBound="-1"
        eType="#//QueteAnnexe" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenes" upperBound="-1"
        eType="#//Scene" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="etats" upperBound="-1"
        eType="#//Situation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declencheurs" upperBound="-1"
        eType="#//Declencheur" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scene">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lieu" eType="#//Lieu"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="maps" upperBound="-1" eType="#//Map"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Archetype" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pnjs" eType="#//PNJ"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="init" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attaque" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
        eType="#//relation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Univers">
    <eStructuralFeatures xsi:type="ecore:EReference" name="campagnes" upperBound="-1"
        eType="#//Campagne" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="archetypes" upperBound="-1"
        eType="#//Archetype" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="organisations" upperBound="-1"
        eType="#//Organisation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lieux" upperBound="-1"
        eType="#//Lieu" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PNJ" eSuperTypes="#//Archetype"/>
  <eClassifiers xsi:type="ecore:EClass" name="PJ" eSuperTypes="#//Archetype"/>
  <eClassifiers xsi:type="ecore:EClass" name="Monstres" eSuperTypes="#//Archetype"/>
  <eClassifiers xsi:type="ecore:EClass" name="Organisation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="maps" upperBound="-1" eType="#//Map"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lieu">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compose" upperBound="-1"
        eType="#//Lieu"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coordonne" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Evenements">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//Evenements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entraine" upperBound="-1"
        eType="#//Situation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declenche" upperBound="-1"
        eType="#//Declencheur"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Declencheur">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entraine" upperBound="-1"
        eType="#//Evenements"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Situation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attends" upperBound="-1"
        eType="#//Evenements"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actif" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueteAnnexe">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declenche" upperBound="-1"
        eType="#//Declencheur" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="maps" upperBound="-1" eType="#//Map"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="active" eType="#//Declencheur"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="relation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="avec" eType="#//Archetype"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TypeRelation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="degre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commentaire" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypeRelation">
    <eLiterals name="connaissance"/>
    <eLiterals name="appreciation" value="1"/>
    <eLiterals name="confiance" value="2"/>
    <eLiterals name="hierarchie" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Map">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lieu" eType="#//Lieu"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
